### ISSUE TITLE
Cannot Install Cymem from wheel?

### ISSUE THREAD

**Issue by pakos47** [explosion/cymem#17]
when trying to install the ".whl" file I always end up Errors like 
"ERROR: cymem-2.0.3-cp38-cp38m-win32.whl is not a supported wheel on this platform."

**Comment by svlandeg** [comment]
Hi @pakos47, what is the operating system you're working on, which version, and what is your Python version ?

**Comment by pakos47** [comment]
Win10, 64-bit and Python 3.8

**Comment by svlandeg** [comment]
Ok, so I guess you need [cymem-2.0.3-cp38-cp38-win_amd64.whl](https://files.pythonhosted.org/packages/8c/1f/43be34e4decc602fae2bda73b05525bc49deff44baeb95611b23a2929195/cymem-2.0.3-cp38-cp38-win_amd64.whl) ?

**Comment by pakos47** [comment]
Tried it already, none of them work unfortunately.

**Comment by svlandeg** [comment]
Ok so you would expect only one of them to work really - the very specific .whl for your system. In your original post you mention `cymem-2.0.3-cp38-cp38m-win32.whl` but the `win32` bit would be incompatible with your 64-bit Windows. Which is why I linked to the (hopefully) correct one. Could you try that one again and paste the full log of your console ?

**Comment by Pierretherenard** [comment]
May be related
Here is what I got when i tried to install on macOS high sierra python 3.5 wheel 0.34.2
 pip install cymem
Collecting cymem
  Using cached cymem-2.0.3.tar.gz (51 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.5/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6t/yj5swk590m7fx49489t_f2sr0000gn/T/pip-install-obc7il24/cymem/setup.py'"'"'; __file__='"'"'/private/var/folders/6t/yj5swk590m7fx49489t_f2sr0000gn/T/pip-install-obc7il24/cymem/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/6t/yj5swk590m7fx49489t_f2sr0000gn/T/pip-install-obc7il24/cymem/pip-egg-info
         cwd: /private/var/folders/6t/yj5swk590m7fx49489t_f2sr0000gn/T/pip-install-obc7il24/cymem/
    Complete output (26 lines):
    Download error on https://pypi.python.org/simple/wheel/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) -- Some packages may not be found!
    No local packages or working download links found for wheel<0.33.0,>=0.32.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6t/yj5swk590m7fx49489t_f2sr0000gn/T/pip-install-obc7il24/cymem/setup.py", line 149, in <module>
        setup_package()
      File "/private/var/folders/6t/yj5swk590m7fx49489t_f2sr0000gn/T/pip-install-obc7il24/cymem/setup.py", line 144, in setup_package
        cmdclass={"build_ext": build_ext_subclass},
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1153, in obtain
        return installer(requirement)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('wheel<0.33.0,>=0.32.0')

**Comment by adrianeboyd** [comment]
Hi, the wheel requirement is no longer needed and is removed from v2.0.5, so I hope the source install is easier now!
